version: "3.8"

services:
  s3:
    container_name: "s3-localstack"
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  aws-cli-make-bucket:
    container_name: "aws-cli-make-bucket"
    image: amazon/aws-cli:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: --endpoint-url=http://s3-localstack:4566 s3 mb s3://edwin-lake-house
    depends_on:
      - s3
  aws-cli-copy-file:
    container_name: "aws-cli-copy-file"
    image: amazon/aws-cli:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: --endpoint-url=http://s3-localstack:4566 s3 cp /customer/landing/customer-1691348231425.json s3://edwin-lake-house/customer/landing/
    volumes:
      - "./customer:/customer:rw"
    depends_on:
      - s3
      - aws-cli-make-bucket
  glue-jupyter:
    container_name: "glue-jupyter"
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    volumes:
      - "~/.aws:/root/.aws:ro" # /home/glue_user/.aws"
      - "./:/home/glue_user/workspace/jupyter_workspace/DataLake:rw"
        # - "./:/home/glue_user/.jupyter"
    environment:
      - DISABLE_SSL=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "4040:4040"
      - "18080:18080"
      - "8998:8998"
      - "8888:8888"
    command: /home/glue_user/jupyter/jupyter_start.sh
    depends_on:
      - s3
      - aws-cli-make-bucket
      - aws-cli-copy-file



